working token index
public-awesome/launchpad pull request #291
Opened 2022-05-31 13:17 UTC by yubrew

saving the shuffled map doesn't make a difference since it'll be hashed the same way in the merkle tree so querying order will not change. requires using an index. data needs both `token_key` and `token_id`. to both query the presence of `token_id` and know which `token_key` to remove.

jhernandez created multiple small shuffles on the front and back of the list, skipping a pseudo-random number of entries.

please double check token key and token id references are correct.

2022-05-31 14:53 UTC, jhernandezb commented on contracts/minter/src/contract.rs
> +        let count = increment_tokens(deps.storage)?;
I made the same comment on Shane's PR, I think  can we avoid saving the counter every time and just do it once the loop ends and use the  index (index,token_id) to save it in TokenInfo? for 10k collections write operations will have some gas costs implications

2022-06-01 15:50 UTC, shanev requested changes
Just some naming suggestions.

2022-06-01 15:50 UTC, shanev commented on contracts/minter/src/state.rs
> +pub fn tokens<'a>() -> IndexedMap<'a, TokenKey, TokenInfo, TokenIndices<'a>> {
```suggestion
pub fn mintable_tokens<'a>() -> IndexedMap<'a, TokenKey, TokenInfo, TokenIndices<'a>> {
```

2022-06-01 15:50 UTC, shanev commented on contracts/minter/src/contract.rs
> +        let token_key = i as u32 + 1;
Do you need to cast as `u32` here?

2022-06-01 22:31 UTC, yubrew commented on contracts/minter/src/contract.rs
> +        let token_key = i as u32 + 1;
yes or else i is usize, wrong type

2022-06-29 23:34 UTC, yubrew commented
takes up too much gas. couldn't even fit on a block

2022-06-29 23:34 UTC, closed without merging