SG-634 SG-617 free wl mints
public-awesome/launchpad pull request #530
Opened 2023-03-23 21:43 UTC by yubrew

2023-03-28 13:58 UTC, shanev requested changes

2023-03-28 14:52 UTC, yubrew commented on contracts/vending-minter/src/contract.rs
> +    if res.mint_price.amount.u128() < factory_params.min_mint_price.amount.u128() {
no, but this lead to finding unchecked parts of base factory and wrong comparisons in vending minter

2023-03-28 15:06 UTC, yubrew commented on contracts/vending-minter/src/contract.rs
> +    if res.mint_price.amount.u128() < factory_params.min_mint_price.amount.u128() {
fixed the code style. comparisons are correct.

2023-03-29 16:01 UTC, shanev approved these changes

2023-03-29 16:02 UTC, merged