SG-619 Add sudo freeze
public-awesome/launchpad pull request #531
Opened 2023-03-27 22:06 UTC by yubrew

2023-03-27 23:58 UTC, shanev requested changes
So old factories will have to be migrated to this in order to be frozen right? So this could use a migrate function that adds the `frozen` field and sets it to true.

May be excessive but here's an example of testing a migration: https://github.com/DA0-DA0/dao-contracts/blob/b09db5a672204229fdd4722c9294b9dd25f4ed03/contracts/proposal/dao-proposal-single/src/testing/migration_tests.rs#L35.

2023-03-28 01:50 UTC, jhernandezb commented
Our marketplace also has an example

https://github.com/public-awesome/marketplace/blob/v1.0.0/contracts/marketplace/src/execute.rs#L1282

Which is more simpler

2023-03-28 01:55 UTC, jhernandezb commented
To speed up this deployment perhaps we can just freeze old code ids for vending-minter and sg721-base

2023-03-28 01:55 UTC, jhernandezb approved these changes

2023-03-28 01:57 UTC, jhernandezb approved these changes

2023-03-28 01:57 UTC, jhernandezb commented on contracts/base-factory/src/contract.rs
> +
move to the top

2023-03-29 14:18 UTC, shanev approved these changes

2023-03-29 14:18 UTC, merged